### ISSUE TITLE
turbot_mod resource constantly showing changes when version set to "*".

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/terraform-provider-turbot#95]
Tempus has given us feedback that when using the latest value for mod installation/maintenance, they often run into issues where even if a mod is on latest version already, TF tries to re-apply and update the mod, which causes errors in the mod and its controls

Still awaiting the  version 

https://turbothq.slack.com/archives/CT39EEU3U/p1595970319453400?thread_ts=1595970264.453300&cid=CT39EEU3U

**Comment by RupeshPatil20** [comment]
Closed under #101
