### ISSUE TITLE
TURBOT_PROFILE environment variable is not being respected. 

### ISSUE THREAD

**Issue by kaidaguerre** [turbot/terraform-provider-turbot#96]
If TURBOT_PROFILE is set, but  TURBOT_ACCESS_KEY, TURBOT_SECRET_KEY and TURBOT_WORKSPACE are not set, and no default profile is set, you get the error 

```No credentials are set - either set TURBOT_ACCESS_KEY, TURBOT_SECRET_KEY and TURBOT_WORKSPACE or populate the file ~/.config/turbot/credentials.yml```

Fix this and verify the precedence of credentials is working and consistent with AWS 

terraform-provider-turbot_v1.6.1. Terraform v0.12.27

**Comment by RupeshPatil20** [comment]
**Case** - No `default` profile set &  no env vars `TURBOT_ACCESS_KEY`, `TURBOT_SECRET_KEY` & `TURBOT_WORKSPACE` set. 
`TURBOT_PROFILE` is **set**.

**Behaviour** -  Provider picked up the profile from `~/.config/turbot/credentials.yml` and successfully created **client**

**Turbot precedence for Credentials**

- Credentials passed in Provider config - 
```
provider "turbot" {
  access_key = "*******"
  secret_key  = "*******"
  workspace  = "*******"
}
```
- Env vars - **TURBOT_ACCESS_KEY**,  **TURBOT_SECRET_KEY**,  **TURBOT_WORKSPACE** 
- TURBOT_PROFILE
**NOTE** - If `TURBOT_PROFILE` is not then default profile will be taken into account.

**AWS Provider Credentials**

- Config Credentials 
- Env Vars 
- `shared_credentials_file` with `profile` in config || `AWS_SHARED_CREDENTIALS_FILE` && `AWS_PROFILE`
